# Generated by Django 5.2 on 2025-04-17 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 17, 10, 40, 24, 338923))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 4, 17, 10, 40, 24, 339010))),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
