# Generated by Django 5.2 on 2025-04-17 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 10, 42, 11, 902547, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 10, 42, 11, 902653, tzinfo=datetime.timezone.utc)),
        ),
    ]
