# Generated by Django 5.2 on 2025-04-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_account_usertodo_todo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodo',
            name='password',
            field=models.CharField(),
        ),
    ]
