# Generated by Django 5.2 on 2025-04-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_usertodo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodo',
            name='email',
            field=models.EmailField(error_messages={'unique': 'email already taken'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='first_name',
            field=models.CharField(error_messages={'max_length': 'invalid lenght first name'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='last_name',
            field=models.CharField(error_messages={'max_length': 'invalid lenght last name'}, max_length=255),
        ),
    ]
