# Generated by Django 5.2 on 2025-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_usertodo_email_alter_usertodo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='first_name',
            field=models.CharField(error_messages={'max_length': 'invalid length first name'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='last_name',
            field=models.CharField(error_messages={'max_length': 'invalid length last name'}, max_length=255),
        ),
    ]
