# Generated by Django 5.2 on 2025-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_account_code_alter_usertodo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
