# Generated by Django 5.2 on 2025-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='actived',
            field=models.BooleanField(default=False),
        ),
    ]
