# Generated by Django 5.2 on 2025-04-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_usertodo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodo',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
