# Generated by Django 5.2 on 2025-04-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_usertodo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code_login',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
    ]
