# Generated by Django 5.2 on 2025-04-23 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_account_code_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertodo',
            name='account_id',
        ),
        migrations.AddField(
            model_name='usertodo',
            name='actived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertodo',
            name='code',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='usertodo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usertodo',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='usertodo',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='FactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todos.usertodo')),
            ],
        ),
    ]
