# Generated by Django 5.2 on 2025-04-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_alter_usertodo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorauth',
            name='code',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
    ]
