# Generated by Django 5.2 on 2025-04-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_alter_factorauth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorauth',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
