# Generated by Django 5.2 on 2025-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_resetpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AlterField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
