# Generated by Django 5.2 on 2025-06-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_delete_account_alter_todo_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
