# Generated by Django 5.2 on 2025-06-20 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0017_todo_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='title must be contains at least 4 alphabetics characters', regex='[a-zA-Z ]{4,255}')]),
        ),
    ]
