# Generated by Django 5.2 on 2025-06-21 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0018_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertodo',
            name='company',
            field=models.CharField(default='internal', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='title must be contains at least 1 alphabetics characters', regex='^[a-zA-Z ]{1,255}$')]),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
