# Generated by Django 5.2 on 2025-06-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0019_usertodo_company_alter_todo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodo',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
