# Generated by Django 5.2 on 2025-06-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0020_alter_usertodo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertodo',
            name='photo',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
