# Generated by Django 5.2 on 2025-06-23 11:14

import django.db.models.deletion
import todos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0021_usertodo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(max_length=255, upload_to=todos.models.set_profil_dir)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.usertodo', unique=True)),
            ],
        ),
    ]
