# Generated by Django 5.2 on 2025-06-24 17:29

import todos.models
import todos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0023_alter_useravatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(height_field=150, max_length=255, upload_to=todos.models.set_profil_dir, validators=[todos.validators.validate_image_mime_type, todos.validators.validate_file_size], width_field=150),
        ),
    ]
