# Generated by Django 5.2 on 2025-06-24 17:56

import todos.models
import todos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0025_alter_useravatar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='height',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='width',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(height_field='height', max_length=255, upload_to=todos.models.set_profil_dir, validators=[todos.validators.validate_image_mime_type, todos.validators.validate_file_size], width_field='width'),
        ),
    ]
